name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git clone --depth 1 https://github.com/kotoba-lang/html.git ../html
      - run: git clone --depth 1 https://github.com/kotoba-lang/css.git ../css
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - run: clojure -M:test
